test

diff --git a/.github/workflows/deploy-docs.yml b/.github/workflows/deploy-docs.yml
--- a/.github/workflows/deploy-docs.yml
+++ b/.github/workflows/deploy-docs.yml
@@ -1,11 +1,8 @@
-
-
 name: 部署文档
 
 on:
   push:
     branches:
-      # 确保这是你正在使用的分支名称
       - master
 
 permissions:
@@ -19,15 +16,11 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-          # 如果你文档需要 Git 子模块，取消注释下一行
-          # submodules: true
 
       - name: 安装 pnpm
         uses: pnpm/action-setup@v2
         with:
-          run_install: true
           version: 8
-
 
       - name: 设置 Node.js
         uses: actions/setup-node@v3
@@ -35,14 +28,18 @@ jobs:
           node-version: 20
           cache: pnpm
 
+      - name: 安装依赖
+        run: pnpm install --frozen-lockfile
+
+      - name: 查看 vue-router 是否安装
+        run: ls -R node_modules/vue-router || echo "vue-router not found"
 
       - name: 构建文档
         env:
           NODE_OPTIONS: --max_old_space_size=8192
-        run: |-
+        run: |
           pnpm run docs:build
           > docs/.vuepress/dist/.nojekyll
-
 
       - name: 部署文档
         uses: peaceiris/actions-gh-pages@v3
